[package]
name = "torrents-csv-service"
version = "0.1.0"
authors = ["Heretic <tylerjobsearch06@gmx.com>"]
edition = "2018"

[dependencies]
actix-web = "4.3.1"
actix-files = "0.6.2"
env_logger = "0.10.0"

serde = "1.0.163"
serde_json = "1.0.96"
serde_derive = "1.0.163"

anyhow = "1.0.71"

tokio-rusqlite = "0.4.0"
tokio = { version = "1.28.1", features = ["full"] }

[dependencies.rusqlite]
version = "0.29.0"
features = ["bundled"]
