version: "3.7"

services:
  torrents-csv:
    image: torrents-csv-server:latest
    restart: unless-stopped
    ports:
      - "8902:8902"
    environment:
      TORRENTS_CSV_DB_FILE: /app/torrents.db
      TORRENTS_CSV_FRONT_END_DIR: /app/dist
